# Generated by Django 5.1.4 on 2025-01-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_user_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesystem',
            name='display_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
