# Generated by Django 5.1.4 on 2025-01-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_filesystem_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filesystem',
            name='opts',
            field=models.TextField(default=''),
        ),
    ]
