# Generated by Django 5.1.4 on 2025-05-16 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_filesystem_opts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(max_length=64)),
                ('filesystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.filesystem')),
            ],
        ),
    ]
