# Generated by Django 5.1.4 on 2025-05-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='id',
        ),
        migrations.AlterField(
            model_name='operation',
            name='hash',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
